### ISSUE TITLE
change in CMakeList.txt

### ISSUE THREAD

**Issue by chochowski** [emjotde/amunmt#16]
I've experienced an issue with cmake not being able to find Threads. It seems that CMake uses short 'C' applications to test/try things. If the CMakeLists.txt states that C++ is used for the project, without also listing C, then some of those shorts tests incorrectly fail, and cmake then thinks those things aren't found. 
Changing PROJECT(amunmt CXX) to PROJECT(amunmt C CXX) seems to help on ubuntu 14.04 with cmake 3.5.2

**Comment by emjotde** [comment]
Thank you, guys. I hope this fixes your problems, we did not encounter this.
