### ISSUE TITLE
Usable in-application BPE support

### ISSUE THREAD

**Issue by emjotde** [emjotde/amunmt#6]
Usable in-application BPE support: specify BPE code location in config file or per command-line switch, perform proper pre- and post-processing without depending on scripts. 

Make sure no buffering occurs.

**Comment by emjotde** [comment]
What about tabbed input? We have the possibility to provide multiple source vocabs, source BPEs should be handled similarly.

**Comment by tomekd** [comment]
I added support for tabbed input. Furthermore, I separated BPE support for input and output. I mean there are two options: bpe and depre. The bpe option takes a path as an argument. 

I don't manage to test APE.

**Comment by emjotde** [comment]
Looks good for me now.
